language: ruby
rvm:
  - 2.3.1
before_install:
  - openssl aes-256-cbc -K $encrypted_595c9df17fac_key -iv $encrypted_595c9df17fac_iv -in hoge.rb.enc -out hoge.rb -d
script: 
  - ruby hoge.rb
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  file:
    - README.md
  on:
    branch: master