language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
before_install:
  - openssl aes-256-cbc -K $encrypted_595c9df17fac_key -iv $encrypted_595c9df17fac_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
script: 
  - ruby hoge.rb
before_deploy:
  - tar cvf secrets.tar hoge.rb prev_epg.csv
  - openssl aes-256-cbc -K $encrypted_595c9df17fac_key -iv $encrypted_595c9df17fac_iv -in secrets.tar -out secrets.tar.enc -e
  - rm secrets.tar .travis.yml hoge.rb prev_epg.csv
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master